### ISSUE TITLE
V operators read output only updated after assignment

### ISSUE THREAD

**Issue by derlunz** [hundredrabbits/Orca-c#13]
I found a peculiarity in orca-c. Variable ('V') operator read outputs are only updated when they occur lexicographically after the first V write operation. 

![orca-variable-assignment](https://user-images.githubusercontent.com/1619633/52365548-061bae00-2a48-11e9-9af5-2fb9be7b55e7.gif)

I would expect for V read operations to work regardless of where they are placed.

**Comment by cancel** [comment]
This is one of the few major differences between orca-js and orca-c. orca-js uses two passes over the grid when executing the code -- and for the `V` operator, storing to the variable is done on the first pass, and reading is done on the second. orca-c works in one pass, so the `V` operator will both store and read immediately. This means that stores need to occur earlier than reads. On the other hand, it means that you can re-use variables and give them different values at different points in your code.

**Comment by derlunz** [comment]
As much as I'd like to explore the 
I have the following concerns with this behavior. It
1) breaks compatibility with orca-js
2) breaks the canvas-style interaction

I consider (1) orca file compatibility desirable. I was recreating from a large patch from a youtube video only to discover that I had to completely restructure it to reproduce the same result.

Ad (2). With the current behavior I also have to carefully look where to place 'control knob' variable assignments and the actual event generating patches that use these variables. Moreover, when moving patches by copy and pasting, they can break in mysterious ways.

I'd propose to change the variable asignment/use behaviour to that of orca-js.

**Comment by cancel** [comment]
Moving chunks of code around can already break as described in 2 in orca-js -- two different writes to the same variable can be reordered, and the later one will 'win'.

It's not possible to change orca-c to behave exactly like orca-js for the `V` operator without rewriting the virtual machine to use a two-pass system. Earlier versions of orca-c used a two-pass system, like orca-js, but we removed it and went with a more simple one-pass system because the code is smaller and more predictable, is more efficient, and is easier to understand and change. If you prefer the orca-js behavior, you should probably use orca-js, but keep in mind that the behavior of orca-js might be changed in the future to match orca-c (and probably not the other way around), as orca-c will become the reference implementation once the features and behavior are settled.

**Comment by derlunz** [comment]
Thank you for the detailed explanation on your implementation. The behavior is still peculiar in my book, but fair enough. I hope to see both projects using the same file format eventually.

Thanks for creating this software gem!
