### ISSUE TITLE
 K operator working differently than nodejs version 

### ISSUE THREAD

**Issue by martinberlin** [hundredrabbits/Orca-c#48]
I just found that the K operator is working differently than in the NodeJs version. To reproduce it just create anything that is reading the Chords from somewhere else like in this example:

https://github.com/martinberlin/Remora/commit/903e371aede39adc06343b9ba50e06170c6b9b1e

When reading this: 
#C..D....#

The K operator will be stuck in the Chord until the new one comes. The behaviour in the other version is that when there is a silence dot, this will also read, which permits playing no note. If I'm correct this is the right way it should be.

**Comment by npisanti** [comment]
actually changing the code to fix this will introduce another difference from orcaJS, so that unassigned variables will be always read anyway as `.`, clearing the southward port

But this change will also fix a problem in orca-c when a bang written to a variable remains stuck into the read variable (just reading with `V`, `K` is fine for reading bangs )

@cancel  @neauoire  what do you think about it? i would be ok with unassigned variable clearing the output when read, in exchange for fixing this and the bang to `V` problem.

new `V` code for trying out:
```c
BEGIN_OPERATOR(variable)
  LOWERCASE_REQUIRES_BANG;
  PORT(0, -1, IN | PARAM);
  PORT(0, 1, IN | PARAM);
  Glyph left = PEEK(0, -1);
  Glyph right = PEEK(0, 1);
  if (left != '.') {
    // Write
    Usz var_idx = safe_index_of(left);
    extra_params->vars_slots[var_idx] = right;
  } else if (right != '.') {
    // Read
    PORT(1, 0, OUT);
    Usz var_idx = safe_index_of(right);
    Glyph result = extra_params->vars_slots[var_idx];
    POKE(1, 0, result);
  }
END_OPERATOR
```
new `K` code :
```c
BEGIN_OPERATOR(konkat)
  LOWERCASE_REQUIRES_BANG;
  Isz len = (Isz)index_of(PEEK(0, -1));
  if (len == 0)
    len = 1;
  PORT(0, -1, IN | PARAM);
  for (Isz i = 0; i < len; ++i) {
    PORT(0, i + 1, IN);
    Glyph var = PEEK(0, i + 1);
    if (var != '.') {
      Usz var_idx = safe_index_of(var);
      if (var_idx != 0) {
        Glyph result = extra_params->vars_slots[var_idx];
        PORT(1, i + 1, OUT);
        POKE(1, i + 1, result);
      }
    }
  }
END_OPERATOR
```

**Comment by neauoire** [comment]
K should always clear the output if the variable is empty, like this:

```
....aV5.
........
....4Kab
......5.
........
....aV..
........
....4Kab
........
........
....aV5.
........
4.X44Kab
......5.
........
....aV..
........
4.X44Kab
........
```

**Comment by npisanti** [comment]
yes that would work with the proposed changes, but the output of the variables will also clear if the they are not assigned, for example if you delete everything and just leave the last
```
4.X44Kab
........
```
even if `a` and `b` are not assigned `K` will clear their output, deleting the 4 written by X

(i'm not sure there is a way to know if a variable in orca-c is not assigned, they are all initialized to `.` before each grid evaluation, we could change that to another not used character for marking not assigned ones, but that could lead to lots of undefined behaviors)

**Comment by npisanti** [comment]
also: having variables set to `.` when not assigned could be useful for livecoding stuff, so if you have a variable assigned to something and you delete all the pattern with the variable you will also automatically clear the receiving `V` and `K`, instead of having them stuck with the last received value.

**Comment by martinberlin** [comment]
Thanks for this one I will try it out!
