### ISSUE TITLE
Linking error on linux

### ISSUE THREAD

**Issue by caropf** [hundredrabbits/Orca-c#61]
I get the following linking error when trying to build ORCA-C:

> /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/orca.77MRyA.ltrans0.ltrans.o: undefined reference to symbol 'keypad'
> /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /lib64/libtinfow.so.6: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status

This can be solved by linking against tinfow:
[0001-fix-linking-error.txt](https://github.com/hundredrabbits/Orca-c/files/4523949/0001-fix-linking-error.txt)

**Comment by cancel** [comment]
I don't know what this is. I don't want to merge it without testing on all other platforms (BSDs, Mac, mingw, cygwin) and other Linux distros because it might break compilation.

**Comment by cancel** [comment]
I guess libtinfo can be split out from ncurses. In order to make the `tool` build script robust against this, we'd need to use `pkg-config`, which opens up a can of worms. (Like we would have to special-case its use on Mac, because homebrew's libncursesw won't show up in it, I think... and I know there are other things I can't think of off the top of my head.)

**Comment by cancel** [comment]
Fixed by 9074100199d9c82b6ee5ca40606c3e2057092350
